const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shits",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 3.5,
      numReview: 10,
      description: "High quality product",
    },
    {
      _id: "2",
      name: "Peter England Slim Shirt",
      category: "Shits",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Peter England",
      rating: 3,
      numReview: 12,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Raymond Slim Shirt",
      category: "Shits",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Raymond",
      rating: 4.3,
      numReview: 100,
      description: "High quality product",
    },
    {
      _id: "4",
      name: "Arro Slim Shirt",
      category: "Shits",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Arro",
      rating: 4.1,
      numReview: 15,
      description: "High quality product",
    },
    {
      _id: "5",
      name: "LP Slim Shirt",
      category: "Shits",
      image: "./images/p1.jpg",
      price: 120,
      brand: "LP",
      rating: 4.6,
      numReview: 100,
      description: "High quality product",
    },
    {
      _id: "6",
      name: "Roadster Slim Shirt",
      category: "Shits",
      image: "./images/p1.jpg",
      price: 120,
      brand: "Roadster",
      rating: 4.0,
      numReview: 101,
      description: "High quality product",
    },
  ],
};

export default data;
